# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章名')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('fine', models.BooleanField(default=False, verbose_name='是否精华')),
                ('sort', models.IntegerField(default=0, verbose_name='顺序')),
                ('cli_num', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Zuozhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zuozheNo', models.CharField(max_length=15, verbose_name='作者编号')),
                ('name', models.CharField(max_length=20, verbose_name='作者姓名')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'zuozhe',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='zuozhe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Zuozhe'),
        ),
    ]
