# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-05 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='check_status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核失败')], default=0, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='zuozhe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Zuozhe', verbose_name='作者'),
        ),
    ]
