# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210109_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=15, verbose_name='用户名')),
                ('xuhao', models.IntegerField(default=0, verbose_name='xuhao')),
                ('pic_path', models.TextField(blank=True, null=True, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'roll_pic',
            },
        ),
    ]
