# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='类别名')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期')),
                ('path_name', models.CharField(max_length=15, verbose_name='种类别名')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': 'category',
            },
        ),
    ]
