# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_tab',
            field=models.BooleanField(default=True, verbose_name='xxxx'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=15, verbose_name='题目'),
        ),
    ]
