# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210109_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期'),
        ),
    ]
