# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-11 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pic_modify_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='pic',
            options={'verbose_name': '轮播图管理', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.AlterModelOptions(
            name='zuozhe',
            options={'verbose_name': '作者管理', 'verbose_name_plural': '作者管理'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='cli_num',
            new_name='click_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fine',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Category', verbose_name='文章类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_tab',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
