# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210111_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='标签名')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'taginfo',
            },
        ),
    ]
