# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_taginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TagInfo', verbose_name='文章标签'),
        ),
    ]
