# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210120_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neirong', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期')),
                ('user', models.CharField(default='匿名', max_length=15, verbose_name='用户名')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Article', verbose_name='评论的文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
