# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-22 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
