# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210122_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='激活'),
        ),
    ]
