# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-23 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210122_2340'),
    ]

    operations = [
    ]
