# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-23 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210123_2159'),
    ]

    operations = [
    ]
