# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210123_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('nick_name', models.CharField(max_length=15, verbose_name='昵称')),
                ('email', models.CharField(max_length=15, verbose_name='邮箱')),
                ('image', models.ImageField(upload_to='user/upload/', verbose_name='头像图片')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成日期')),
                ('is_start', models.BooleanField(default=False, verbose_name='激活')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='neirong',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户名'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
