# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-23 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210124_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_man',
        ),
    ]
