# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-28 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210125_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='密码'),
        ),
    ]
